src/billing/urls.py
from django.conf.urls import url

from .views import (BillingUpgradeView,
                    BillingHistoryTransactionListView,
                    CancelSubscriptionView)

urlpatterns = [
    url(r'^$', BillingUpgradeView.as_view(), name='upgrade'),
    url(r'^history/$', view=BillingHistoryTransactionListView.as_view(), name="list"),
    url(r'^cancel/$', view=CancelSubscriptionView.as_view(), name="cancel"),
]

src/notifications/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import NotificationListView, ReadRedirectView, AjaxNotificationsView

urlpatterns = [
    url(r'^$', view=NotificationListView.as_view(), name="list"),
    url(r'^read/(?P<pk>\d+)/$', ReadRedirectView.as_view(), name='read'),
    url(r'^ajax_notifications/$', AjaxNotificationsView.as_view(), name='ajax_notifications'),
]

src/srvup/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from srvup.views import HomeView, Contact
from srvup.api.views import HomeAPIView
from users.views import AccountTemplateView


urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^contact/$', Contact.as_view(), name="contact"),
    url(r'^account/$', AccountTemplateView.as_view(), name="account_profile"),
    url(r'^billing/', include("billing.urls", namespace="billing")),
    url(r'^categories/', include("videos.urls", namespace="categories")),
    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^notifications/', include("notifications.urls", namespace="notifications")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/auth/token/$', 'rest_framework_jwt.views.obtain_jwt_token'),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/categories/', include("videos.api.urls", namespace="category")),
    url(r'^api/comments/', include("comments.api.urls", namespace="comment")),
    url(r'^api/$', HomeAPIView.as_view(), name="home_api"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/videos/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import CategoryListView, VideoDetailView, VideoListView

urlpatterns = [
    url(r'^$', view=CategoryListView.as_view(), name="list"),
    url(r'^(?P<slug>[\w-]+)/$', view=VideoListView.as_view(), name="detail"),
    url(r'^(?P<cat_slug>[\w-]+)/(?P<slug>[\w-]+)/$', view=VideoDetailView.as_view(), name="video_detail"),
]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>srvup Project | {% block head_title %}{% endblock head_title %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    {% include "extra_head_info.html" %}
    <style>
      {% block style %}
      {% endblock style %}
      html {
        position: relative;
        min-height: 100%;
      }
      body {
        /* Margin bottom by footer height */
        margin-bottom: 60px;
      }
      .container-fluid {
        margin-top: 50px;
      }
      .footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        /* Set the fixed height of the footer here */
        height: 60px;
        background-color: #f5f5f5;
      }
    </style>
    
  </head>

  <body>

    
    {% include "navbar.html" %}
   
    <div class="container-fluid">
      {% block jumbotron %}
      {% endblock jumbotron %}
      {% for message in messages %}
        <div class="alert {% if 'error' in message.tags %}alert-danger{% else %}alert-success{% endif %} col-sm-8 col-sm-offset-2">
          {{ message }}
        </div>
      {% endfor %}
      <div class="col-sm-8 col-sm-offset-2">
      {% block content %}
      
      {% endblock content %}
      </div>

    </div> <!-- /container -->
    <footer class="footer footer-fixed-bottom">
      <div class="container">
        <p class="text-muted">&copy; 2016 Srvup Project</p>
      </div>
    </footer>

  {% include "javascript.html" %}
  <script>
    {% block jquery %}
      $(document).ready(function() {
      });
    {% endblock jquery %}
  </script>
  <script>
    $(document).ready(function() {
      $(".notifications-toggle").click(function () {
        var request = $.ajax({
          method: "GET",
          url: "{% url 'notifications:ajax_notifications' %}",
          data: {
            notifications: "{{ notifications }}",
            count: "{{ count }}"
          },
        });

        request.done(function(data) {
          console.log(data)
          $("#dropdown-notifications").html("");
          var count = data.count
          var url = '{% url "notifications:list" %}'
          $(data.notifications).each(function() {
            var link = this;
            $("#dropdown-notifications").append("<li>" + link + "</li>");
          });
          $("#dropdown-notifications").append("<li><a href='" + url + "'>View All</a></li>");
        });

        request.fail(function(jqXHR, textStatus) {
          console.log(textStatus)
          console.log(jqXHR)
          if (jqXHR.status == 404) {
              alert("Page not found.")
            } else if (jqXHR.status == 404) {
              alert("You must be logged in to do this.")
            } else {
              alert("There was an error with your request. Please try again.")
            }
        });
      });
    });
  </script>
  </body>
</html>

src/templates/contact.html
{% extends "base.html" %}

{% block content %}
<h1>Contact Us</h1>
{% endblock content %}

src/templates/extra_head_info.html
{% load staticfiles %}
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!-- <link href="http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"> -->

<!-- Custom styles for this template -->
<!-- <link href="http://getbootstrap.com/examples/navbar-static-top/navbar-static-top.css" rel="stylesheet"> -->

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

src/templates/javascript.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"><\/script>')</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!--<script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>-->

<script src="https://js.braintreegateway.com/v2/braintree.js"></script>

src/templates/navbar.html
<style>
{% block style %}
.badge {
  background: #444;
  position: relative;
  top: -6px;
  left: -8px;
  padding-bottom: 5px;
  padding-top: 4px;
}
.navbar {
  background-color: #000673; 
  border-color: #000673;
}
.navbar-default .navbar-nav>li>a, .navbar-default .navbar-brand {
  color: #FFFFFF; 
}
{% endblock style %}
</style>
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container col-sm-8 col-sm-offset-2">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><b>srvup</b></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'categories:list' %}">Categories</a></li>
        <li><a href="{% url 'billing:upgrade' %}">Enroll</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

      {% if user.is_authenticated %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle notifications-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-inbox" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-badge" aria-hidden="true">0</span>
          </a>
          <ul class="dropdown-menu notifications" id="dropdown-notifications">

          </ul>
        </li>
        <li><a href="{% url 'account_profile' %}">Account</a></li>
        <li><a href="{% url 'account_logout' %}">Logout</a></li>
      {% else %}
        <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
        <li><a href="{% url 'account_login' %}">Login</a></li>
      {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>